name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: DEV
      url: 'https://dbc-c19c33d8-8658.cloud.databricks.com/?o=452580029438744#folder/3905951248849306'
    steps:
      - name: Deploy
        run: echo I am deploying!! 
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: QA
      url: 'https://dbc-c19c33d8-8658.cloud.databricks.com/?o=452580029438744#folder/3961602762188887'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: PROD
      url: 'https://dbc-c19c33d8-8658.cloud.databricks.com/?o=452580029438744#folder/3961602762188899'
    steps:
      - name: Deploy
        run: echo I am deploying! 
